<a href="https://colab.research.google.com/github/noh-yujeong/SPARTACODING-education-content/blob/main/3%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5_01_%EB%94%A5%EB%9F%AC%EB%8B%9D_XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam,SGD

In [ ]:
#XOR 데이터 셋
x_data=np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
y_data=np.array([[0],[1],[1],[0]],dtype=np.float32)

print(x_data)
print(y_data)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
[[0.]
 [1.]
 [1.]
 [0.]]


In [ ]:
#XOR 이진 논리 회귀
model=Sequential([
                  Dense(1,activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer=SGD(lr=0.1))

model.fit(x_data,y_data,epochs=1000,verbose=0)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
y_pred=model.predict(x_data)
print(y_pred)

[[0.49861583]
 [0.50016934]
 [0.4993962 ]
 [0.50094974]]


In [ ]:
#XOR딥러닝(MLP)

model=Sequential([
                  Dense(8,activation='relu'),
                  Dense(1,activation='sigmoid'),
])

model.compile(loss='binary_crossentropy',optimizer=SGD(lr=0.1))

model.fit(x_data,y_data,epochs=1000,verbose=0)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
y_pred=model.predict(x_data)
print(y_pred)

[[0.04230487]
 [0.9879514 ]
 [0.9872538 ]
 [0.04230487]]


In [ ]:
#keras Functional API

import numpy as np
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam, SGD

In [ ]:
input=Input(shape=(2,))
hidden=Dense(8,activation='relu')(input)
output=Dense(1,activation='sigmoid')(hidden)

model=Model(inputs=input,outputs=output)
model.compile(loss='binary_crossentropy',optimizer=SGD(lr=0.1))
model.summary()


Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 2)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 24        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 9         
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model.fit(x_data,y_data,epochs=1000,verbose=0)
y_pred=model.predict(x_data)
print(y_pred)

[[0.03652331]
 [0.9895941 ]
 [0.98974574]
 [0.03652331]]
